### ISSUE TITLE
Support for Backup Channels using FFMPEG as buffer.

### ISSUE THREAD

**Issue by xtinct101** [Threadfin/Threadfin#16] opened 2022-10-13 00:27 UTC
Adding in Github for tracking.

When selecting FFMPEG as the buffer in Threadfin, threadfin does not cycle through the backup channel if one is set.

Add support for Backup Channels using FFMPEG as the buffer.

**Comment by Fyb3roptik** [comment] 2022-10-17 19:11
Duplicate of #12

**Closed by Fyb3roptik** 2022-10-17 19:11 UTC

**Comment by xtinct101** [comment] 2022-10-17 19:18
I don't believe this is a duplicate of #12.
#12 is regarding Threadfin, while using Threadfin Buffer, not cycling through a backup channel if said backup channel every errored out.
