### ISSUE TITLE
V1.1.8+ fails to start web server and crashes

### ISSUE THREAD

**Issue by 2fst4u** [Threadfin/Threadfin#269] opened 2024-05-26 06:48 UTC
**Describe the bug**
After updating to any version higher than 1.1.7, the container fails to start.

**Server (please complete the following information):**
- OS Ubuntu 22.04.4 running docker version in kubernetes k3s 1.29.4+k3s1
- Arch  Intel 64 Bit
- Threadfin Version and Build as per description 

**To Reproduce**
1. Update container 

**Expected behavior**
Container runs

**Screenshots**
Nil

**Desktop (please complete the following information):**
Container fails agnostic of browser 

**Additional context**
The kubernetes log states:
```
For help run: /home/threadfin/bin/threadfin -h



2024/05/26 06:43:03 [Threadfin] [WARNING] Don't run this as Root!

2024/05/26 06:43:03 [Threadfin] Version:                1.1 Build: 8

2024/05/26 06:43:03 [Threadfin] Database Version:       0.5.0

2024/05/26 06:43:03 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 2

2024/05/26 06:43:03 [Threadfin] Hostname:               threadfin-0

2024/05/26 06:43:03 [Threadfin] System Folder:          /home/threadfin/conf/

2024/05/26 06:43:03 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json

2024/05/26 06:43:03 [Threadfin] Temporary Folder:       /tmp/threadfin/2023-11-66P1-DK3A0I/

2024/05/26 06:43:03 [Threadfin] GitHub:                 https://github.com/Threadfin

2024/05/26 06:43:03 [Threadfin] Git Branch:             Main [Threadfin]

2024/05/26 06:43:03 [Threadfin] SSDP / DLNA:            true

2024/05/26 06:43:03 BRANCH:  Main

2024/05/26 06:43:03 TAG LATEST:  1.1.12

2024/05/26 06:43:03 FILE:  https://github.com/Threadfin/Threadfin/releases/download/1.1.12/Threadfin_linux_amd64

2024/05/26 06:43:03 [Threadfin] [WARNING] Threadfin update available

2024/05/26 06:43:03 [Threadfin] UUID:                   2023-11-66P1-DK3A0I

2024/05/26 06:43:03 [Threadfin] Tuner (Plex / Emby):    10

2024/05/26 06:43:03 [Threadfin] EPG Source:             XEPG

2024/05/26 06:43:03 [Threadfin] Plex Channel Limit:     480

2024/05/26 06:43:03 [Threadfin] Unfiltered Chan. Limit: 480

2024/05/26 06:43:03 [Threadfin] Backup Path:            /home/threadfin/conf/backup/

2024/05/26 06:43:03 [Threadfin] Backup file:            /home/threadfin/conf/backup/threadfin_auto_backup_20240526_0643.zip

2024/05/26 06:43:03 [Threadfin] Download:               https://i.mjh.nz/nz/raw-tv.m3u8

2024/05/26 06:43:03 [Threadfin] Check File:             https://i.mjh.nz/nz/raw-tv.m3u8

2024/05/26 06:43:03 [Threadfin] Save File:              https://i.mjh.nz/nz/raw-tv.m3u8 [ID: MSOFANJ6I8T1WX2BVCM7]

2024/05/26 06:43:03 [Threadfin] Download:               https://i.mjh.nz/nz/epg.xml

2024/05/26 06:43:03 [Threadfin] Check File:             https://i.mjh.nz/nz/epg.xml

2024/05/26 06:43:04 [Threadfin] Save File:              https://i.mjh.nz/nz/epg.xml [ID: XDBBTV7VL7YP7F1ZR6OD]

2024/05/26 06:43:04 [Threadfin] All streams:            41

2024/05/26 06:43:04 [Threadfin] Active streams:         41

2024/05/26 06:43:04 [Threadfin] Filter:                 0

2024/05/26 06:43:04 [Threadfin] DVR IP:                 threadfin.[redacted]:34400

2024/05/26 06:43:04 [Threadfin] Web Interface:          http://threadfin.[redacted]:34400/web/ | Threadfin is also available via the other 3 IP's.

2024/05/26 06:43:04 [Threadfin] XEPG:                   Parse XMLTV file: Freeview

2024/05/26 06:43:04 [Threadfin] [ERROR] listen tcp 10.1.0.100:34400: bind: cannot assign requested address (Web server could not be started.) - EC: 1001

2024/05/26 06:43:04 [Threadfin] [ERROR] listen tcp 10.1.0.100:34400: bind: cannot assign requested address () - EC: 0

[33m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[33m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[32m[0m[0m[0m[31m[0m[31m[0m
```

I note there are references to v1.1.12 in the logs. I'm pinning my container version, it correctly states the version in the pod description.

**Comment by marcelGoerentz** [comment] 2024-05-27 06:19
Have a look at #267 seems to be a duplicated issue.

**Comment by 2fst4u** [comment] 2024-05-27 06:22
Different version numbers though, hence why I didn't consider it a duplicate. I've narrowed down this specific version that affected me one by one.

There's also no resolution to that issue, only a fork to a different repo which I wouldn't consider a fix.

-------- Original Message --------

**Comment by marcelGoerentz** [comment] 2024-05-27 06:28
There is a docker version

**Comment by 2fst4u** [comment] 2024-05-27 06:29
Regardless changing to a fork isn't a fix.

**Comment by marcelGoerentz** [comment] 2024-05-27 06:31
I didn't consider it a fix, it is a workaround.

**Comment by Fyb3roptik** [comment] 2024-05-28 16:08
Duplicate of #253

**Closed by Fyb3roptik** 2024-05-28 16:08 UTC
