### ISSUE TITLE
startup stuck at Check File stage and will not continue

### ISSUE THREAD

**Issue by Tau512** [Threadfin/Threadfin#356] opened 2024-09-01 09:17 UTC
I've updated to the latest current version (1.2.5, i think upgraded from 1.2.3), and it appears to be having issues with the check file stage.
CPU is pegged at 100% of 1 core for >10 minutes and does not continue to make the service available.

I auto update via watchtower, which occured at 3-4am this morning. i woke up to find the high CPU usage on my threadfin container so appears that this does not correct itself even after being left for hours or container restarted.

Running via Docker, log:

```
2024-09-01T09:02:36.663101763Z For help run: /home/threadfin/bin/threadfin -h

2024-09-01T09:02:36.663321205Z 

2024-09-01T09:02:36.666894185Z 2024/09/01 10:02:36 [Threadfin] [WARNING] Don't run this as Root!

2024-09-01T09:02:36.667469785Z 2024/09/01 10:02:36 [Threadfin] Version:                1.2 Build: 5

2024-09-01T09:02:36.667906463Z 2024/09/01 10:02:36 [Threadfin] Database Version:       0.5.0

2024-09-01T09:02:36.668362053Z 2024/09/01 10:02:36 [Threadfin] System IP Addresses:    IPv4: 2 | IPv6: 1

2024-09-01T09:02:36.668782998Z 2024/09/01 10:02:36 [Threadfin] Hostname:               547400ff352b

2024-09-01T09:02:36.669272328Z 2024/09/01 10:02:36 [Threadfin] System Folder:          /home/threadfin/conf/

2024-09-01T09:02:36.671369688Z 2024/09/01 10:02:36 [Threadfin] Load Settings:          /home/threadfin/conf/settings.json

2024-09-01T09:02:36.676355220Z 2024/09/01 10:02:36 [Threadfin] Temporary Folder:       /tmp/threadfin/2024-07-XWT1-NS3BAC/

2024-09-01T09:02:36.676635764Z 2024/09/01 10:02:36 [Threadfin] GitHub:                 https://github.com/Threadfin

2024-09-01T09:02:36.676674084Z 2024/09/01 10:02:36 [Threadfin] Git Branch:             Main [Threadfin]

2024-09-01T09:02:36.676680217Z 2024/09/01 10:02:36 [Threadfin] SSDP / DLNA:            true

2024-09-01T09:02:36.679500455Z 2024/09/01 10:02:36 [Threadfin] [WARNING] Updates are disabled in the settings

2024-09-01T09:02:36.679569051Z 2024/09/01 10:02:36 [Threadfin] UUID:                   2024-07-XWT1-NS3BAC

2024-09-01T09:02:36.679576685Z 2024/09/01 10:02:36 [Threadfin] Tuner (Plex / Emby):    1

2024-09-01T09:02:36.679581218Z 2024/09/01 10:02:36 [Threadfin] EPG Source:             XEPG

2024-09-01T09:02:36.679585759Z 2024/09/01 10:02:36 [Threadfin] Plex Channel Limit:     480

2024-09-01T09:02:36.679590248Z 2024/09/01 10:02:36 [Threadfin] Unfiltered Chan. Limit: 480

2024-09-01T09:02:36.679594935Z 2024/09/01 10:02:36 [Threadfin] Backup Path:            /home/threadfin/conf/backup/

2024-09-01T09:02:36.730228254Z 2024/09/01 10:02:36 [Threadfin] Backup file:            /home/threadfin/conf/backup/threadfin_auto_backup_20240901_1002.zip

2024-09-01T09:02:36.731241268Z 2024/09/01 10:02:36 [Threadfin] Download:               http://URL_REMOVED/get.php?username=USER_REMOVED&password=PASS_REMOVED&type=m3u_plus&output=ts

2024-09-01T09:02:36.731883160Z 2024/09/01 10:02:36 PROXY URL:  

2024-09-01T09:02:50.530925078Z 2024/09/01 10:02:50 [Threadfin] Header filename:        tv_channels_USER_REMOVED_plus.m3u

2024-09-01T09:02:57.380278316Z 2024/09/01 10:02:57 [Threadfin] Check File:             http://URL_REMOVED/get.php?username=USER_REMOVED&password=PASS_REMOVED&type=m3u_plus&output=ts
```

i havent tried reverting to 1.2.4 (i need the https://github.com/Threadfin/Threadfin/commit/d5ce984597abe00c8d5f791c66b6828db13e5291 fix) yet, i'll try that later today.

edit: doesnt appear to be a provider issue. i wget'd the download/check File URL on another machine and file downloaded without error and appears to be correct so my IPTV service appears good.

**Comment by Caligo82** [comment] 2024-09-01 11:08
Reverting to 1.2.2 solved the issue for me.

**Comment by Tau512** [comment] 2024-09-01 11:27
i've gone back to 1.2.3 which allows threadfin to start ok (aside from the periodic crashing i get due to https://github.com/Threadfin/Threadfin/issues/341)
1.2.4 & 1.2.5 broken.

`-e THREADFIN_DEBUG=3` isn't giving any more info at the CHECK FILE stage either.

if it helps @Fyb3roptik, i could probably sanitize & privately provide my `tv_channels_USER_REMOVED_plus.m3u` file (i assume this the the file used in Download and Check File stages).

**Comment by Fyb3roptik** [comment] 2024-09-01 13:30
Duplicate of #354

**Closed** 2024-09-01 13:31 UTC
