### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by bweezy21** [Threadfin/Threadfin#83] opened 2023-06-03 19:32 UTC
Windows defender flags latest release as a trojan.

Trojan:Win32/Wacatac.B!ml

**Comment by Fyb3roptik** [comment] 2023-06-03 20:13
Duplicate of #80

**Closed** 2023-06-03 20:13 UTC

**Comment by bweezy21** [comment] 2023-06-03 20:28
apologies, i searched open issues. i see this one is closed.
