### ISSUE TITLE
Replace PPV channels title/desc: setting not working properly

### ISSUE THREAD

**Issue by BrandonP135711** [Threadfin/Threadfin#277] opened 2024-06-03 23:18 UTC
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
The "Replace PPV channels title/desc:" setting works for initial setup but does not work on subsequent channel name changes. If I understand the setting properly, if my provider changes the names of channels this setting should update those channels descriptions to be the new name in the xepg export. 

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu] Windows 11
- Arch [e.g. Intel 64 Bit] 64 Bit
- Threadfin Version and Build [to be found in the Threadfin log] 1.1.14

**To Reproduce**
1. Import M3U and XML
2. Check mapping for channel names and descriptions
3. Change channel name
4. See no update to description on xepg

**Expected behavior**
I would expect the new name to be used in the description on the xepg

**Screenshots**
![image](https://github.com/Threadfin/Threadfin/assets/171631266/80a7fc86-0dce-4a66-95a2-ff9acd41d0a1)

![image](https://github.com/Threadfin/Threadfin/assets/171631266/8b08f05a-1064-4b0c-a152-706b789c2216)

For context this event took place back in January:
![image](https://github.com/Threadfin/Threadfin/assets/171631266/ced36a63-c6f8-45eb-93f1-d14a2d8f9d6b)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 125

**Additional context**
This may be an enhancement request, but it would also be helpful if that description was updated in the channel mappings screen:
![image](https://github.com/Threadfin/Threadfin/assets/171631266/fc27c404-4b5f-4c14-9bac-83b646950d19)

**Comment by Fyb3roptik** [comment] 2024-06-04 05:28
What version are you on? This is not happening for me on latest

**Comment by Fyb3roptik** [comment] 2024-06-25 15:42
I am not able to reproduce this. Maybe delete the xml and m3u files it generates (~/.threadfin/data/threadfin.m3u and threadfin.xml)

**Comment by BrandonP135711** [comment] 2024-06-25 22:48
> I am not able to reproduce this. Maybe delete the xml and m3u files it generates (~/.threadfin/data/threadfin.m3u and threadfin.xml) and see if that solves it?

I'll try and see what happens

**Comment by BrandonP135711** [comment] 2024-06-25 23:12
I think i figured it out. the tvg-name field in the generated xepg.json is not getting updated. i deleted it and had it regenerated and that has worked for now. I will keep an eye on it as these channel names change.

**Comment by ceb0610** [comment] 2024-06-28 14:24
Seeing the same issue and deleting the xepg is only a temporary fix. My PPV channels don't have the option to "Change Channel Name".

**Comment by Fyb3roptik** [comment] 2024-07-11 15:35
Closing as this should now be resolved

**Closed by Fyb3roptik** 2024-07-11 15:35 UTC
