### ISSUE TITLE
EPG channel mappings not recognized because <channel> tags are missing from generated XMLTV

### ISSUE THREAD

**Issue by blackwind** [Threadfin/Threadfin#59] opened 2023-04-06 03:24 UTC
**Describe the bug**
I'm unable to view guide data in Jellyfin and unable to add my tuner to Plex at all because \<channel\> tags are missing from the generated XMLTV. When I manually copy the \<channel\> tags from the original XMLTV files into the generated file, mappings are recognized as expected. All channels are properly mapped in Threadfin and show up green.

Here's what happens when I try to add the tuner to Plex:

![Plex](https://user-images.githubusercontent.com/889881/230261897-846c53c1-12c4-4a95-81ee-9ce7ed10e109.png)

This is my first time setting up IPTV, so I allow for the possibility that I'm just an idiot; from my view at this current moment, though, it seems Threadfin's guide implementation is completely broken, at least for the providers I'm using (mjh).

**Server (please complete the following information):**
- OS: Docker
- Arch: x86_64
- Threadfin Version and Build: 1.0 Build 7

**To Reproduce**
1. Add an M3U and XMLTV, mapping channels if needed, filtering below 480 if needed
2. Add tuner to Plex, providing Threadfin's XMLTV link when asked

**Expected behavior**
Plex should automatically associate the tuner channels it found with their matching EPG channels. Without channel IDs present in the generated XMLTV file, this apparently can't happen.

**Comment by Fyb3roptik** [comment] 2023-04-12 16:12
Can I get a sample of the raw XMLTV you are inputting? Channel is definitely a mapped thing

**Comment by blackwind** [comment] 2023-04-12 16:25
https://i.mjh.nz/SamsungTVPlus/us.xml

**Comment by Fyb3roptik** [comment] 2023-04-13 15:59
I am not able to reproduce this. All of the XML generated by Threadfin has channel data in it

**Comment by blackwind** [comment] 2023-04-14 02:08
From a brand new instance of Threadfin:

1. Load the web interface
2. Choose the default number of tuners
3. Submit https://i.mjh.nz/SamsungTVPlus/us.m3u8
4. Submit https://i.mjh.nz/SamsungTVPlus/us.xml
5. Go to Mapping and observe all channels are successfully mapped
6. Open `threadfin.xml` and observe there are no \<channel\> tags

I'm able to reproduce 100% of the time.

**Comment by blackwind** [comment] 2023-04-26 04:40
@Fyb3roptik Can I get you to take another look at this using the instructions above?

**Comment by Fyb3roptik** [comment] 2023-05-02 04:26
Absolutely! If I can reproduce it I'll fix it

**Comment by Fyb3roptik** [comment] 2023-05-21 17:56
I think this is due to the m3u missing tvg-name. There is another ticket for this, so I will fix it then retest this to see if that resolves it

**Comment by Fyb3roptik** [comment] 2023-05-22 04:34
Fixed in 1.0.11

**Closed by Fyb3roptik** 2023-05-22 04:34 UTC
Labels: bug
