### ISSUE TITLE
Tuner doesn't release free unit when stream and backup channel cannot stream

### ISSUE THREAD

**Issue by Ondrashek** [Threadfin/Threadfin#145] opened 2023-09-27 16:41 UTC
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
When you play stream and stream won't play and backup channel won't play too, tuner still have active connection and won't start another stream

**Server (please complete the following information):**
Linux Docker 10 (18)

**To Reproduce**
Play stream and backup channel when is not live
Switch to another stream which is live
It stucks to last stream which is not live
You must restart whole Threadfin

**Expected behavior**
Tuner should release connection after is stream is absolutely dead

**Desktop (please complete the following information):**
Linux

**Comment by Nostradamus1973** [comment] 2023-10-18 08:05
Good morning everyone,,

I'm having this very same issue.
The tuner plays the stream and never lets go; yesterday,  I was ONE person  who managed to occupy 10 streams at once with ONE streaming box simply by changing my tuner over a few minutes. When this happens there's an xTeve message stating you've reached the stream limit. At that point a full docker container restart is needed.
I really like using this script over xTeve and hope this can be addressed soon.

Is there an unstable release ready to go? If this is fixed in an unstable release, can I please test it?

Thank you for your help and time.

**Comment by Nostradamus1973** [comment] 2023-10-26 13:29
Good morning Everyone,

I'm still experiencing this issue on the latest release of Threadfin. Would anyone know if this has been addressed or not?

Thank you and have a nice day.

**Comment by Nostradamus1973** [comment] 2023-10-30 19:26
Update:
As much as Github is a great resource to get help, I can say with certainty that if you try the Threadfin Discord group you'll find that they are extremely helpful, it isn't just an active discord, it's thriving; the mods, developer, and members are extremely knowledgeable and not only tell you how to do something, they explain the mechanisms going into whatever train-of-thought is going on, that way we users can understand how things work and possibly even help ourselves in the future because of what is gleaned from the Threadfin Discord.

Just to reiterate, there's nothing wrong with Github, I'm just mentioning their discord group as an excellent resource for real-time help.

Have a great day

**Comment by jbf154** [comment] 2023-10-31 20:07
I can fairly reliably reproduce this issue.  Here are the options I'm using:

- Client: Plex
- Buffer: FFmpeg
- Threadfin buffer size: 2MB
- FFmpeg options: `-hide_banner -loglevel error -err_detect ignore_err -reconnect 1 -reconnect_on_network_error 1 -reconnect_on_http_error 1 -reconnect_streamed 1 -reconnect_delay_max 4294 -i [URL] -c copy -flags:a +global_header -f mpegts pipe:1`

Steps to reproduce:

1. Tune a known good channel to verify threadfin/Plex are working correctly
2. Tune to a bad channel. A bad channel in this case is a URL that returns a 404 error after ~10 seconds. I've mocked this on https://app.beeceptor.com/console/vtpi3. Point your channel to `https://vtpi3.free.beeceptor.com/404please`
3. Observe the logs:

```
threadfin  | 2023/10/31 15:56:52 [Threadfin] Buffer:                 true [ffmpeg]
threadfin  | 2023/10/31 15:56:52 [Threadfin] Buffer Size:            2048 KB
threadfin  | 2023/10/31 15:56:52 [Threadfin] Channel Name:           BadChannel
threadfin  | 2023/10/31 15:56:52 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
threadfin  | 2023/10/31 15:56:53 [Threadfin] Streaming Status:       Playlist: M3U - Tuner: 1 / 1
threadfin  | 2023/10/31 15:56:53 [Threadfin] FFMPEG path:            /usr/bin/ffmpeg
threadfin  | 2023/10/31 15:56:53 [Threadfin] Streaming URL:          https://vtpi3.free.beeceptor.com/404please
threadfin  | 2023/10/31 15:56:53 [Threadfin] FFMPEG:                 Processing data
threadfin  | 2023/10/31 15:56:53 [Threadfin] Streaming Status:       Receive data from FFMPEG
threadfin  | 2023/10/31 15:57:03 [Threadfin] FFMPEG log:             https://vtpi3.free.beeceptor.com/404please: Server returned 404 Not Found
threadfin  | 2023/10/31 15:57:03 RESTARTING STREAM DUE TO ERROR
threadfin  | 2023/10/31 15:57:03 [Threadfin] FFMPEG path:            /usr/bin/ffmpeg
threadfin  | 2023/10/31 15:57:03 [Threadfin] Streaming URL:          https://vtpi3.free.beeceptor.com/404please
threadfin  | 2023/10/31 15:57:03 [Threadfin] FFMPEG:                 Processing data
threadfin  | 2023/10/31 15:57:03 [Threadfin] Streaming Status:       Receive data from FFMPEG
threadfin  | 2023/10/31 15:57:13 [Threadfin] Streaming Status:       Client has terminated the connection
threadfin  | 2023/10/31 15:57:13 [Threadfin] Streaming Status:       Channel: BadChannel (Clients: 0)
threadfin  | 2023/10/31 15:57:14 [Threadfin] FFMPEG log:             https://vtpi3.free.beeceptor.com/404please: Server returned 404 Not Found
threadfin  | 2023/10/31 15:57:27 [Threadfin] Buffer:                 true [ffmpeg]
threadfin  | 2023/10/31 15:57:27 [Threadfin] Buffer Size:            2048 KB
threadfin  | 2023/10/31 15:57:27 [Threadfin] Channel Name:           US: SYFY
threadfin  | 2023/10/31 15:57:27 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
threadfin  | 2023/10/31 15:57:27 [Threadfin] Streaming Status:       Playlist: M3U - Tuner: 1 / 1
threadfin  | 2023/10/31 15:57:48 [Threadfin] Streaming Status:       Client has terminated the connection
threadfin  | 2023/10/31 15:57:48 [Threadfin] Streaming Status:       Channel: US: SYFY (Clients: 0)
threadfin  | 2023/10/31 15:58:02 [Threadfin] Buffer:                 true [ffmpeg]
threadfin  | 2023/10/31 15:58:02 [Threadfin] Buffer Size:            2048 KB
threadfin  | 2023/10/31 15:58:02 [Threadfin] Channel Name:           GoodChannel
threadfin  | 2023/10/31 15:58:02 [Threadfin] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
threadfin  | 2023/10/31 15:58:03 [Threadfin] Streaming Status:       Playlist: M3U - Tuner: 1 / 1
threadfin  | 2023/10/31 15:58:23 [Threadfin] Streaming Status:       Client has terminated the connection
threadfin  | 2023/10/31 15:58:23 [Threadfin] Streaming Status:       Channel: US: SYFY (Clients: 0)
```

I was observing `htop` while doing this testing and `ffmpeg` is never launched for the 'GoodChannel' stream. You can also see that it never logs the stream URL for 'GoodChannel'.

**Closed** 2023-11-02 20:21 UTC

**Comment by hacktek** [comment] 2023-11-25 04:47
I don't think this is fixed. I have 15 streams across 3 different providers / 3 playlists, today I came home to all streams tied up but when I checked the providers, zero connections were actually being used but threadfin continued to report that all tuners were full. I don't know what got it into this state, however.
