### ISSUE TITLE
Import m3u channel numbers

### ISSUE THREAD

**Issue by Miniz199922** [Threadfin/Threadfin#91] opened 2023-06-11 13:53 UTC
Need a way to import with channel numbers or edit the channel numbers. 

#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**

**Server (please complete the following information):**
- OS [e.g. Linux - Ubuntu]
- Arch [e.g. Intel 64 Bit]
- Threadfin Version and Build [to be found in the Threadfin log]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Fyb3roptik** [comment] 2023-06-11 14:57
Duplicate of #81

**Closed by Fyb3roptik** 2023-06-11 14:57 UTC
