### ISSUE TITLE
v 1.1.2 blocking remote access to Threadfin interface

### ISSUE THREAD

**Issue by GeekSpeak79** [Threadfin/Threadfin#267] opened 2024-05-23 00:34 UTC
#### Please first read the [documentation](https://github.com/Threadfin/Threadfin/blob/main/en/configuration.md). Problems affecting the client, e.g. Plex or Emby should be reported there in the forum.

**Describe the bug**
Commit b27dfdd (v 1.1.2)  code line 362 the logic to ignore suffix .1 is resulting in threadfin web interface being blocked for server that has WSL installed. 
Note: WSL is installed to support docker environment, however Threadfin is running natively in Windows, and NOT via docker container.

It appears that when Threadfin scans networks, it uses the Hyper-V firewall IP as it's primary Interface IP, which happens to have a .1 suffix.

On local server, the Threadfin can only be access used the Hyper-V assigned IP (172.18.240.1:34400/web), all other options (LocalHost, 127.0.0.1, public IP) are non responsive. Regression to V1.1.1 resolves the issue.

**Server (please complete the following information):**
- OS Windows 10
- Arch Intel 64-bit
- Threadfin Version and Build 1.1 build 2 and beyond.

**To Reproduce**
1. install WSL on Windows 10 
2. Docker is running as well,but I believe its the mere presence of the WSL Hyper-V firewall that triggers the issue.

**Expected behavior**
Expect to access Threadfin interface from 127.0.0.1:34400/web on local server, but fails. All similar connections fail other than using the hyper-vfirewall IP Eg http://172.18.240.1:34400/web

**Screenshots**
Screenshots available upon request

**Desktop (please complete the following information):**

**Additional context**
I am running Threadfin natively, and not via a docker container.

**Comment by YodaDaCoda** [comment] 2024-05-23 04:48
I'm seeing a similar problem inside docker. Not sure where these addresses are coming from, I'd prefer it to bind to `0.0.0.0`.

```
2024/05/23 14:47:43 [Threadfin] [ERROR] listen tcp 104.21.37.106:34400: bind: cannot assign requested address (Web server could not be started.) - EC: 1001
2024/05/23 14:47:43 [Threadfin] [ERROR] listen tcp 104.21.37.106:34400: bind: cannot assign requested address () - EC: 0
```

**Comment by marcelGoerentz** [comment] 2024-05-23 10:55
> I'm seeing a similar problem inside docker. Not sure where these addresses are coming from, I'd prefer it to bind to `0.0.0.0`.
> 
> ```
> 2024/05/23 14:47:43 [Threadfin] [ERROR] listen tcp 104.21.37.106:34400: bind: cannot assign requested address (Web server could not be started.) - EC: 1001
> 2024/05/23 14:47:43 [Threadfin] [ERROR] listen tcp 104.21.37.106:34400: bind: cannot assign requested address () - EC: 0
> ```

Try my fork, there it should work. [fork](https://github.com/marcelGoerentz/Threadfin)

**Comment by GeekSpeak79** [comment] 2024-05-23 16:19
> > I'm seeing a similar problem inside docker. Not sure where these addresses are coming from, I'd prefer it to bind to `0.0.0.0`.
> > ```
> > 2024/05/23 14:47:43 [Threadfin] [ERROR] listen tcp 104.21.37.106:34400: bind: cannot assign requested address (Web server could not be started.) - EC: 1001
> > 2024/05/23 14:47:43 [Threadfin] [ERROR] listen tcp 104.21.37.106:34400: bind: cannot assign requested address () - EC: 0
> > ```
> 
> Try my fork, there it should work. [fork](https://github.com/marcelGoerentz/Threadfin)

@marcelGoerentz Looks like there's quite a few changes in that fork; Boolean syntax, error reporting, Added some IP fields to the UI etc.

**Comment by marcelGoerentz** [comment] 2024-05-23 19:53
@GeekSpeak79 Good too hear 😄

**Comment by marcelGoerentz** [comment] 2024-05-24 10:02
Hey, I've pushed some docker images. you can pull them like this:

`docker pull mgoerentz/threadfin:latest`

**Comment by Renkyz** [comment] 2024-05-26 03:54
I also have a similar problem and no idea what's causing it. I run Threadfin natively using the .exe on a box running Windows Server 2022, I normally access Threadfin from a different PC running Windows 10 on the same local network but after updating to 1.1.2, I could no longer access it. The only way I found that worked was by using 127.0.0.1:34400 directly from the server machine itself which is rather inconvenient for me.

To make matters worse, this also impacted my Plex Server's ability to see Threadfin as I set that up using the servers specific IP address (192.168.0.xx) rather than localhost 127.0.0.1 which is probably smarter but it's a bit of a pain in the backside to switch that now.

I was running 1.0.26 without the issue so I've reverted back to that version and everything is working as it was before for me again.

**Comment by marcelGoerentz** [comment] 2024-05-26 05:01
Try the .exe from my fork and tell us if it is working for you.

**Comment by Renkyz** [comment] 2024-05-26 05:18
> Try the .exe from my fork and tell us if it is working for you.

Just tried it and it does work.

**Comment by Fyb3roptik** [comment] 2024-05-28 16:08
Duplicate of #253

**Closed by Fyb3roptik** 2024-05-28 16:08 UTC
