### ISSUE TITLE
Threadfin not booting since today - log frozen in 'check file'

### ISSUE THREAD

**Issue by tobiasredel** [Threadfin/Threadfin#354] opened 2024-08-31 11:58 UTC
Hi, since today (after a docker reboot) my threadfin instance is not booting up, looking at the logs it says:

2024/08/31 13:56:16 [Threadfin] Header filename:        ....
2024/08/31 13:56:22 [Threadfin] Check File:                  ...

So it downloads the m3u as normal but then freezes in the status check file

**Comment by SMOKINxxJOE** [comment] 2024-08-31 13:57
I am having the same issue.

**Comment by morpheus302** [comment] 2024-08-31 14:41
Same Problem here. Reverted back to threadfin:1.2.0

**Comment by mm98** [comment] 2024-08-31 15:09
I've noticed the same. Removed everything (of cause didn't have any backup) and reverted back to v1.2.2 and it works again. 
I couldn't find a log or anything showing what the problem was (using 75% CPU and almost all RAM - QNAP NAS).

**Comment by Fyb3roptik** [comment] 2024-08-31 17:57
More than likely you have a ton of 24/7 channels. You'll need to get rid of those as now it's updating the incoming m3u

**Comment by morpheus302** [comment] 2024-08-31 21:45
can you please develop on " as now it's updating the incoming m3u"? Is is the "Probe Channel Feature" mentioned in the changelog?
How can we remove 24/7 channels on the fly?

**Comment by tobiasredel** [comment] 2024-08-31 23:28
> More than likely you have a ton of 24/7 channels. You'll need to get rid of those as now it's updating the incoming m3u

what does that mean? I guess a lot of us have an external m3u provider and we use threadfin to filter / etc. if not threadfin required to pre-filter m3u ... isnt that the initial purpose of threadfin? i love this project and i would love to see a fix for this

**Comment by mm98** [comment] 2024-09-01 05:37
> More than likely you have a ton of 24/7 channels. You'll need to get rid of those as now it's updating the incoming m3u

I love this project! I think this will cause trouble for lots of people, since they are not in control of an external M3U. Wouldn't it be more "correct" to do it on the `filtered` channels instead? This would limit the amount of channels greatly. Just an suggestion ....

**Comment by Fyb3roptik** [comment] 2024-09-01 13:29
This has nothing to do with probing. I'm adding tvg-id where it's blank except it's duplicating the channels. People with 24/7 channels are getting those duplicated which is why it's taking forever.

I'll have a fix on Monday or Tuesday when I'm at my computer

**Comment by chandz05** [comment] 2024-09-01 16:55
oh wow I just started using Threadfin and was wondering why so many people rate it over xTeVe, when it couldn't even load up my relatively small m3u. Spun up v1.2.2 and it's working like a charm! Thanks for that suggestion, and I hope this gets fixed soon!

**Comment by eboddington** [comment] 2024-09-02 07:50
Could this be the same issue I'm having when importing a playlist rather than at startup, where Threadfin eventually gets killed for OOM?

**Comment by Fyb3roptik** [comment] 2024-09-02 13:54
Don't use 1.2.5 revert to one that works until 1.2.6 comes out

**Comment by eboddington** [comment] 2024-09-02 16:32
> Don't use 1.2.5 revert to one that works until 1.2.6 comes out

I've reverted to 1.2.2, but with Threadfin running in Docker, when loading a 110MB M3U, the memory usage balloons so much that the entire VM running Docker (7GB memory) gets killed for OOM

**Comment by KevinBoone90** [comment] 2024-09-02 18:17
Thank you for this topic, I thought for some reason my installation went bust - good to see that I am not the only one getting issues. I know I have a massive m3u list but never had these resource issues (eating up CPU and RAM). Hope they fix it soon, love this selfhosted app!

**Comment by tobiasredel** [comment] 2024-09-03 17:16
I guess, 1.2.6. should fix this issue - i have updated to 1.2.6 but its still booting up for more than one hour with 80-90% CPU usage

**Comment by Pepeanuts** [comment] 2024-09-03 19:22
Same for me (used on unRAID).

**Comment by cjs321** [comment] 2024-09-03 21:38
1.2.5 and 1.2.6 also don't work for me, they take way too long to boot.
1.2.2 boots within a minute or so, 1.2.5 and 1.2.6 was taking way longer.
Please fix this?

**Comment by deku-m** [comment] 2024-09-04 10:30
Also have the same issue hanging on check_file in version 1.2.6

**Comment by davidclaeysquinones** [comment] 2024-09-04 12:37
I can also confirm 1.2.6 doesn't fix the issue.

**Comment by Fyb3roptik** [comment] 2024-09-05 12:35
Can you confirm if your m3u contains 24/7 channels? If so, then that is the problem. Threadfin now assigns a tvg-id to those that are blank, which probably means it's having to go through the massive m3u

**Comment by tobiasredel** [comment] 2024-09-05 12:39
There are some 24/7 channels in there, yes. Can this be fixed somehow from threadfin? Because i am not sure yet how i should handle it otherwise (as its an external m3u which would then need to be prefiltered)

**Comment by davidclaeysquinones** [comment] 2024-09-05 12:46
I don't really understand what you mean by 24/7 channels.
The playlist I'm using is massive (about 10.000 streams).
I don't really understand why a tvg-id needs to be assigned.

All I know is that up until 1.2.2 everything is just working fine.
In later releases new features are added which is nice.
But normally behavior off the application should not change or this should be clearly stated in the release notes.

Whether the whole tvg-id is needed I don't know. If it really is I would suggest it is only done on channels that are filtered in order to reduce processing.

**Comment by tobiasredel** [comment] 2024-09-05 16:11
As a workaround iam using https://github.com/euzu/m3u-filter to filter down my external m3u and then give it to threadfin, but would be great to have a fix in threadfin

**Comment by davidclaeysquinones** [comment] 2024-09-05 18:09
At least that's a workaround.
Still I'm not going to update threadfin. I'm hoping there is a way that existing performance an functionality can be kept.
I'm not looking forward to add yet another layer of failure, even more when before I had no need to do so.

**Comment by eboddington** [comment] 2024-09-05 18:34
I’ve found reverting to 1.2.0 to be stable again

**Comment by Tau512** [comment] 2024-09-05 19:44
> Can you confirm if your m3u contains 24/7 channels? If so, then that is the problem. Threadfin now assigns a tvg-id to those that are blank, which probably means it's having to go through the massive m3u

what would be the solution if we wanted the 24/7 channels available?

According to my list, I've 103 channels with "24/7" in their name. About half are in my "active streams" list on v1.2.3. I don't understand how this is causing such a massive issue at boot.

I can't say i'm interesting in running it via m3u-filter. I chose threadfin as it appeared to be everything i needed in 1 tool.

**Comment by davidclaeysquinones** [comment] 2024-09-06 06:32
> Can you confirm if your m3u contains 24/7 channels? If so, then that is the problem. Threadfin now assigns a tvg-id to those that are blank, which probably means it's having to go through the massive m3u

Could you please explain the reasoning behind the tvg-id assignment ?

**Comment by Fyb3roptik** [comment] 2024-09-06 18:33
I need you to understand me clearly. I will not be tailoring this software around your shitty providers who give you a massive m3u with 10,000 channels and most of them useless 24/7 channels. The rest of us have proper m3u's that are not clogged up. Please pre-filter it with a service like m3u4u or something like it. Stop asking for a fix for this

**Closed by Fyb3roptik** 2024-09-06 18:33 UTC

**Comment by davidclaeysquinones** [comment] 2024-09-06 19:00
> I need you to understand me clearly. I will not be tailoring this software around your shitty providers who give you a massive m3u with 10,000 channels and most of them useless 24/7 channels. The rest of us have proper m3u's that are not clogged up. Please pre-filter it with a service like m3u4u or something like it. Stop asking for a fix for this

You might be right about the reasons why the issue can't be solved. And I might agree or not.
However I don't think your response displays the right attitude. 

One thing is explaining why something is not possible, another saying someone is asking for something taylor made. As a matter of fact there is some functional regression and this is not clearly documented . If you don't document regression on something you shouldn't be frustrated when users update and complain about it.

**Comment by mm98** [comment] 2024-09-06 19:28
> One thing is explaining why something is not possible, another saying someone is asking for something taylor made. As a matter of fact there is some functional regression and this is not clearly documented . If you don't document regression on something you shouldn't be frustrated when users update and complain about it.

This is open-source and he is in no way obligated to document anything. I'm a dev my self and i find this comment so frustrating. He decided to fork an existing project and adjust it. Nothing is holding you or anyone back from using v1.2.3 which works.

**Comment by davidclaeysquinones** [comment] 2024-09-06 19:51
> > One thing is explaining why something is not possible, another saying someone is asking for something taylor made. As a matter of fact there is some functional regression and this is not clearly documented . If you don't document regression on something you shouldn't be frustrated when users update and complain about it.
> 
> This is open-source and he is in no way obligated to document anything. I'm a dev my self and i find this comment so frustrating (_"i want / need it fixed"_). He decided to fork an existing project and adjust it. Nothing is holding you or anyone back from using v1.2.3 which works.

I think communication is key.
You're absolutely right about him doing this work in his free time . But once you have a user base and want to keep it you need to document changes to some degree.

I'm also a dev and definitely see why my comments could be frustrating. But on the other hand this is also a bit frustrating as an user

**Comment by Tau512** [comment] 2024-09-06 20:03
> Nothing is holding you or anyone back from using v1.2.3 which works.

2 points here:
1) yes there is an issue stopping (some) of us using older versions. https://github.com/Threadfin/Threadfin/issues/341. fixed for >=1.2.4 but it introduces the issue discussed in here.
2) this is also the entire point of this thread. this new feature for tvg-id has regressed.
You've admitted the issue is 'fixed in an older version', i'd imagine to any normal person that would imply newer versions are broken.

maybe it's me, but i see an entire thread here of people with issues, it's not isolated to 1 or 2 users.

Yes the dev can do as he sees fit. It's their software, time and desires. us users are just along for the ride.

fwiw, i wasnt on the attack in my last message, but appears it may've come across as that. Applogies if i've offended anyone, that wasnt the intention.

ateotd, Fyb3roptik has spoken, closed as "complete" so time to find another tool that works for me as this one no longer functions in my scenario.

**Comment by jsbear** [comment] 2024-09-06 20:15
Wow this thread took an interesting turn, I'll leave it at that.

**Comment by tobiasredel** [comment] 2024-09-07 06:58
I just wanted to state that using m3u4u is a great proposal from @Fyb3roptik. It 1st solves the issue (which i think is not because threadfin is doing something wrong) but our m3us are sorted, named, grouped in a way which is not standard and / or rubbish and 2nd gives far more granular renaming, sorting ability outside of threadfin. Then use threadfin for the bare purpose of mapping epg, proxying & serving to emby, etc.

**Comment by davidclaeysquinones** [comment] 2024-09-07 07:04
At that point the filtering capabilities of threadfin become useless but yeah

**Comment by morpheus302** [comment] 2024-09-11 00:27
You can use an alternative project called Stream Master [[](url)](https://github.com/SenexCrenshaw/StreamMaster)

**Comment by jsbear** [comment] 2024-09-12 19:37
> You can use an alternative project called Stream Master [](https://github.com/SenexCrenshaw/StreamMaster)

I have tried StreamMaster, although the interface is nice and the potential with this project looks positive, I experienced more buffering issues than usual plus I could not figure out epg and related guide data, it worked at first then stopped working, no idea what was going on or how to fix.  Possibly user error, couldn't find much information re: setup, settings etc.  Documentation seems light.  Will keep an eye on it for sure.

**Comment by cenunix** [comment] 2024-09-24 07:23
> I need you to understand me clearly. I will not be tailoring this software around your shitty providers who give you a massive m3u with 10,000 channels and most of them useless 24/7 channels. The rest of us have proper m3u's that are not clogged up. Please pre-filter it with a service like m3u4u or something like it. Stop asking for a fix for this

It's clearly an issue because a number of people here are unable to use threadfin now, is there any way you could add an option that would allow us with shitty providers to continue using the app?

**Comment by davidclaeysquinones** [comment] 2024-09-24 07:47
You can use an intermediate tool like [https://github.com/euzu/m3u-filter](https://github.com/euzu/m3u-filter)  or other online tools.
Ofc this complicates the deployment because you're adding another layer into the stack.

I've been experiencing the so called duplication issues and they are quite annoying and detrimental to the overall experience.
From a technical standpoint the easiest thing is assigning unique id's if they are not present instead of working out a whole logic structure to distinguish unique channels. Specially in garbage playlists this is very difficult.

However I don't understand why we are called entitled (or annoying) for complaining that we can't use a tool we were using like we already were.  If you make the decision to not support an existing use case because it's technically getting to complicated you need to communicate this properly in the release notes. Ideally you explain the reason so that users at least know were you're coming from. Otherwise you make sure you test things properly and that you don't have regression in existing use cases.

Yes the application is open source and no retribution is received, but your application will have no future if you don't communicate properly. Proper communication shouldn't be a big ask.

At this point I've spend hours trying to migrate channels through m3u-filter so that when finished I can migrate to one of the newer versions of threadfin. I'm not really pleased about this outcome because of the required effort but at least I get from where the devs are coming. I just wish they communicated properly and not after the fact when a lot of us were complaining.

For now I'll keep  using threadfin but I definitely will keep an eye open for other alternatives in order to simplify my stack.

**Comment by foux** [comment] 2024-10-20 20:02
This issue is just absolutely ridiculous, and @Fyb3roptik is absolutely laughable. I heard he is working on a Jellyfin replacement. LOOOOOL, it will be funny with this mentality.

**Comment by Fyb3roptik** [comment] 2024-10-20 20:08
People that don't understand how tech works laughing at programmers. Ok buddy. Go cry somewhere else

**Comment by dotbanana** [comment] 2024-11-06 14:20
> > I need you to understand me clearly. I will not be tailoring this software around your shitty providers who give you a massive m3u with 10,000 channels and most of them useless 24/7 channels. The rest of us have proper m3u's that are not clogged up. Please pre-filter it with a service like m3u4u or something like it. Stop asking for a fix for this
> 
> It's clearly an issue because a number of people here are unable to use threadfin now, is there any way you could add an option that would allow us with shitty providers to continue using the app?

For us shitty-provider-peasants i found this tool here: 
https://github.com/sonroyaalmerol/m3u-stream-merger-proxy  
This does everything threadfin does, and even more.  
Is basically a complete replacement.
