### ISSUE TITLE
Can we get a docker for unraid?

### ISSUE THREAD

**Issue by IllMethods** [Threadfin/Threadfin#122] opened 2023-08-05 04:16 UTC
Hello

I'm not sure how to create one, but could you do this please? This seems a lot better than xteve

**Comment by Mlitz** [comment] 2023-08-05 05:35
I have a templet you can use.
I am still working though the settings to get it to work inside of plex though

**Comment by IllMethods** [comment] 2023-08-05 05:38
I'm not sure how to get the docker template to work within unraid, it isn't something I've had to do before. 

What is wrong with it working with plex? I use plex, emby and jellyfin

**Comment by Mlitz** [comment] 2023-08-05 05:45
I had someone help me with the templet.

you need to create a new file /boot/config/plugins/dockerMan/templates-user/my-threadfin.xml and paste

`<?xml version="1.0"?>
<Container version="2">
  <Name>threadfin</Name>
  <Repository>fyb3roptik/threadfin:latest</Repository>
  <Registry>https://hub.docker.com/r/fyb3roptik/threadfin/tags</Registry>
  <Network>media.server</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://github.com/Threadfin/Threadfin/issues</Support>
  <Project>https://github.com/Threadfin/Threadfin</Project>
  <Overview/>
  <Category>MediaServer:Video</Category>
  <WebUI>http://[IP]:[PORT:34400]/web</WebUI>
  <TemplateURL/>
  <Icon/>
  <ExtraParams/>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1691196777</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="Host Port 1" Target="34400" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">34400<>
  <Config Name="THREADFIN_PORT" Target="THREADFIN_PORT" Default="" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask=">
  <Config Name="THREADFIN_DEBUG" Target="THREADFIN_DEBUG" Default="" Mode="" Description="Set Threadfin debug level [ 0-3 ] Default: 0=OFF" Type=">
  <Config Name="THREADFIN_BRANCH" Target="THREADFIN_BRANCH" Default="" Mode="" Description="Set Threadfin git branch (main / beta)" Type="Variable>
  <Config Name="CONF" Target="/home/threadfin/conf" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">
</Container>`

I cant get the file path in Plex to link to Threadfin.

**Comment by IllMethods** [comment] 2023-08-05 06:02
I'm not sure I'll be able to do this but I'll give it a go after dinner. Docker is new tertiary for me

**Comment by Fyb3roptik** [comment] 2023-08-05 06:18
Here is what chatgpt spit out for my dockerfile

```xml
<Container version="2">
  <Name>threadfin</Name>
  <Repository>yourusername/threadfin:latest</Repository>
  <Registry>https://hub.docker.com/r/yourusername/threadfin/</Registry>
  <Network>bridge</Network>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://github.com/Threadfin/Threadfin</Support>
  <Project/>
  <Overview>Dockerized Threadfin</Overview>
  <Category/>
  <WebUI>http://[IP]:[PORT:34400]</WebUI>
  <TemplateURL/>
  <Icon>icon.png</Icon>
  <Config Name="AppData" Target="/home/threadfin" Default="/mnt/user/appdata/threadfin" Mode="rw" Description="AppData" Type="Path" Display="always" Required="true" Mask="false"></Config>
  <Config Name="Cache" Target="/home/threadfin/cache" Default="/mnt/user/appdata/threadfin/cache" Mode="rw" Description="Cache" Type="Path" Display="always" Required="true" Mask="false"></Config>
  <Config Name="Conf" Target="/home/threadfin/conf" Default="/mnt/user/appdata/threadfin/conf" Mode="rw" Description="Conf" Type="Path" Display="always" Required="true" Mask="false"></Config>
  <Config Name="Temp" Target="/home/threadfin/temp" Default="/mnt/user/appdata/threadfin/temp" Mode="rw" Description="Temp" Type="Path" Display="always" Required="true" Mask="false"></Config>
  <Config Name="PORT" Target="34400" Default="34400" Mode="" Description="Threadfin Port" Type="Port" Display="always" Required="true" Mask="false"></Config>
  <Environment>
    <Variable>
      <Name>THREADFIN_PORT</Name>
      <Value>34400</Value>
    </Variable>
    <Variable>
      <Name>TZ</Name>
      <Value>America/New_York</Value>
    </Variable>
  </Environment>
</Container>
```

**Comment by Fyb3roptik** [comment] 2023-08-05 06:21
If this works let me know and I'll add it to the repo and to the unRAID template place so it's searchable

**Comment by Mlitz** [comment] 2023-08-05 06:24
@Fyb3roptik the one I posed works. it is up and running in Unraid, I just cant get Plex to link to it

**Comment by IllMethods** [comment] 2023-08-05 06:24
I actually have no real experience with docker, I can install them within Unraid but before that, I just pulled straight from github on ubuntu server and ran things that way. Docker is very new to me and Unraid is the only place I can use it, except I'm not even sure if I can make my own templates to use within my server itself.

**Comment by IllMethods** [comment] 2023-08-05 06:26
> @Fyb3roptik the one I posed works. it is up and running in Unraid, I just cant get Plex to link to it

Where? I can't find it in unraid

**Comment by Fyb3roptik** [comment] 2023-08-05 06:27
> @Fyb3roptik the one I posed works. it is up and running in Unraid, I just cant get Plex to link to it

Feel free to do a PR and add it into a template folder or however it says to put it in github

**Comment by Mlitz** [comment] 2023-08-05 06:36
I will do a PR this weekend, Thanks

**Comment by IllMethods** [comment] 2023-08-05 08:01
I just tried the windows version. This is a bit nicer than xteve, only issue I've seen is what you said. Plex just won't load, emby and jellyfin on the other hand have no issue at all

**Comment by pharpe** [comment] 2023-08-07 21:59
> I had someone help me with the templet.
> 
> you need to create a new file `/boot/config/plugins/dockerMan/templates-user/my-threadfin.xml` and paste

I created the my-threadfin.xml but when I create a new container and select that template nothing is populated.  Is there a format issue?

**Comment by pharpe** [comment] 2023-08-07 22:01
![image](https://github.com/Threadfin/Threadfin/assets/1161350/287fa5b3-aae5-47de-9355-a560e7c32af4)
![image](https://github.com/Threadfin/Threadfin/assets/1161350/039b7072-2a72-4e8d-85cb-d25aab163085)

**Comment by IllMethods** [comment] 2023-08-08 02:34
> ![image](https://user-images.githubusercontent.com/1161350/258935272-287fa5b3-aae5-47de-9355-a560e7c32af4.png) ![image](https://user-images.githubusercontent.com/1161350/258935293-039b7072-2a72-4e8d-85cb-d25aab163085.png)

I'm getting the same result. I can manually fill it in but I can not change the port. The chat gpt one seems perfect until you go to start it, then get an error and fails

**Comment by Mlitz** [comment] 2023-08-08 03:14
I am new to this too, try this one

[my-threadfin.zip](https://github.com/Threadfin/Threadfin/files/12286902/my-threadfin.zip)

If the Path does not get formatted correctly use this format

![Screenshot 2023-08-07 200331](https://github.com/Threadfin/Threadfin/assets/24885063/09f0a790-55b7-49a2-afb6-1dc6f5bc3f18)

**Comment by IllMethods** [comment] 2023-08-08 03:20
This one works

**Comment by Mlitz** [comment] 2023-08-08 03:23
did you have to reformat the path? or did that work too?

**Comment by IllMethods** [comment] 2023-08-08 03:26
> did you have to reformat the path? or did that work too?

Nope, I just did a copy and paste, then created the new dock from template.

**Comment by Fyb3roptik** [comment] 2023-08-08 05:37
Closing this. Thanks for helping and I look forward to the PR!

**Comment by IllMethods** [comment] 2023-08-09 20:15
Do your streams work in plex? Mine would show but wouldn't actually stream

**Comment by pharpe** [comment] 2023-08-09 22:07
The updated template worked.  Plex recognized Threadfin and loads streams fine.

**Comment by IllMethods** [comment] 2023-08-09 22:09
Just to be clear, it will load up the guide, and play the stream? I tried from the windows version and it would not load the steam.

**Comment by pharpe** [comment] 2023-08-09 22:16
Yeah you have to delete all DVRs.  
![image](https://github.com/Threadfin/Threadfin/assets/1161350/3d888c5a-3179-498a-aee6-17865e8fdcd6)
Then when you click Setup DVR again you should see the Threadfin (i only have a few mapped because I'm messing with EPG mapping)
![image](https://github.com/Threadfin/Threadfin/assets/1161350/ed05c53e-c56f-4111-8918-7a68f45dd2a5)

**Comment by loperator692** [comment] 2023-09-11 15:45
Thank you for this thread!  The template works great and everything seems to be steaming.  Really appreciate your work on this.

**Comment by Mlitz** [comment] 2023-09-11 15:57
> Thank you for this thread! The template works great and everything seems to be steaming. Really appreciate your work on this.

This needs to be added to the community applications for easy install but that requires a bit of work that I just don't have the time for right now. Ibracorp has a good video on the way to do it if someone wants to try.

**Comment by OcifferAction** [comment] 2023-09-21 19:59
I created a simple icon in MS Paint for UnRAID if anyone wants to use it. [https://i.imgur.com/OfnCV9z.png](url)

**Comment by Fyb3roptik** [comment] 2023-09-26 16:52
Adding to CA

**Closed by Fyb3roptik** 2023-09-26 16:52 UTC

**Comment by isaacolsen94** [comment] 2023-10-27 17:08
This isn't showing up in CA for me, Is it under a different name or do I need a specific version of Unraid?

**Comment by ubermick** [comment] 2023-12-27 13:47
> This isn't showing up in CA for me, Is it under a different name or do I need a specific version of Unraid?

I can find it under "Dockerhub" but nothing showing in CA. Tried the install via Dockerhub, but not having much success, alas.

**Comment by mhopps108** [comment] 2024-01-07 17:26
> > This isn't showing up in CA for me, Is it under a different name or do I need a specific version of Unraid?
> 
> I can find it under "Dockerhub" but nothing showing in CA. Tried the install via Dockerhub, but not having much success, alas.

Same issues here - no success with adding the template above. Having it in community apps would be amazing.

**Comment by pharpe** [comment] 2024-01-08 17:34
I think the problem is adding anything to CA is an offical Unraid process and whoever does that has to agree to create a dedicated thread and support that application going forward.  It's not a one and done task.  If you put Theadfin on CA then you become the Unraid Threadin dev have to deal with all the issues.  So if the original docker publisher pushes breaking changes, and people have issues, then you have to research and respond.
